import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Area, AreaChart } from 'recharts';
const ChartContainer = ({ title, data, dataKey, color = '#4ADE80', unit = '', timeRange, onTimeRangeChange, isLoading = false, fill = true, }) => {
    const timeRanges = ['24h', '7d', '30d'];
    const CustomTooltip = ({ active, payload, label }) => {
        if (active && payload && payload.length) {
            return (_jsxs("div", { className: "bg-slate-800/95 backdrop-blur-xl border border-slate-700 rounded-lg p-3 shadow-xl", children: [_jsx("p", { className: "text-slate-400 text-sm mb-1", children: label }), _jsxs("p", { className: "text-white font-bold text-lg", children: [payload[0].value, " ", _jsx("span", { className: "text-sm text-slate-400 font-normal", children: unit })] })] }));
        }
        return null;
    };
    if (isLoading) {
        return (_jsxs("div", { className: "bg-slate-800/50 backdrop-blur-xl rounded-2xl p-6 border border-slate-700/50", children: [_jsxs("div", { className: "flex items-center justify-between mb-6", children: [_jsx("div", { className: "h-6 bg-slate-700 rounded w-40 animate-pulse" }), _jsx("div", { className: "flex gap-2", children: [1, 2, 3].map((i) => (_jsx("div", { className: "h-8 bg-slate-700 rounded-lg w-16 animate-pulse" }, i))) })] }), _jsx("div", { className: "h-64 bg-slate-700/50 rounded-xl animate-pulse" })] }));
    }
    return (_jsxs("div", { className: "bg-slate-800/50 backdrop-blur-xl rounded-2xl p-6 border border-slate-700/50 hover:border-emerald-500/30 transition-all duration-300", children: [_jsxs("div", { className: "flex items-center justify-between mb-6", children: [_jsx("h3", { className: "text-lg font-semibold text-white", children: title }), _jsx("div", { className: "flex bg-slate-900/50 rounded-lg p-1", children: timeRanges.map((range) => (_jsx("button", { onClick: () => onTimeRangeChange(range), className: `px-4 py-1.5 rounded-md text-sm font-medium transition-all ${timeRange === range
                                ? 'bg-emerald-600 text-white shadow-lg'
                                : 'text-slate-400 hover:text-white'}`, children: range }, range))) })] }), _jsx("div", { className: "h-64", children: _jsx(ResponsiveContainer, { width: "100%", height: "100%", children: fill ? (_jsxs(AreaChart, { data: data, margin: { top: 10, right: 10, left: 0, bottom: 0 }, children: [_jsx("defs", { children: _jsxs("linearGradient", { id: `gradient-${dataKey}`, x1: "0", y1: "0", x2: "0", y2: "1", children: [_jsx("stop", { offset: "5%", stopColor: color, stopOpacity: 0.3 }), _jsx("stop", { offset: "95%", stopColor: color, stopOpacity: 0 })] }) }), _jsx(CartesianGrid, { strokeDasharray: "3 3", stroke: "#334155" }), _jsx(XAxis, { dataKey: "time", stroke: "#64748b", fontSize: 12, tickLine: false, axisLine: { stroke: '#334155' } }), _jsx(YAxis, { stroke: "#64748b", fontSize: 12, tickLine: false, axisLine: { stroke: '#334155' }, tickFormatter: (value) => `${value}${unit}` }), _jsx(Tooltip, { content: _jsx(CustomTooltip, {}) }), _jsx(Area, { type: "monotone", dataKey: dataKey, stroke: color, strokeWidth: 2, fill: `url(#gradient-${dataKey})`, animationDuration: 500 })] })) : (_jsxs(LineChart, { data: data, margin: { top: 10, right: 10, left: 0, bottom: 0 }, children: [_jsx(CartesianGrid, { strokeDasharray: "3 3", stroke: "#334155" }), _jsx(XAxis, { dataKey: "time", stroke: "#64748b", fontSize: 12, tickLine: false, axisLine: { stroke: '#334155' } }), _jsx(YAxis, { stroke: "#64748b", fontSize: 12, tickLine: false, axisLine: { stroke: '#334155' }, tickFormatter: (value) => `${value}${unit}` }), _jsx(Tooltip, { content: _jsx(CustomTooltip, {}) }), _jsx(Line, { type: "monotone", dataKey: dataKey, stroke: color, strokeWidth: 2, dot: false, activeDot: { r: 6, fill: color, stroke: '#fff', strokeWidth: 2 }, animationDuration: 500 })] })) }) })] }));
};
export default ChartContainer;
